##################################################
# file: Service_server.py
#
# skeleton generated by "ZSI.generate.wsdl2dispatch.ServiceModuleWriter"
#      /usr/bin/wsdl2py -b service.wsdl
#
##################################################

from ZSI.schema import GED, GTD
from ZSI.TCcompound import ComplexType, Struct
from Service_types import *
from ZSI.ServiceContainer import ServiceSOAPBinding

# Messages  
FECAESolicitarSoapIn = GED("http://ar.gov.afip.dif.FEV1/", "FECAESolicitar").pyclass

FECAESolicitarSoapOut = GED("http://ar.gov.afip.dif.FEV1/", "FECAESolicitarResponse").pyclass

FECompTotXRequestSoapIn = GED("http://ar.gov.afip.dif.FEV1/", "FECompTotXRequest").pyclass

FECompTotXRequestSoapOut = GED("http://ar.gov.afip.dif.FEV1/", "FECompTotXRequestResponse").pyclass

FEDummySoapIn = GED("http://ar.gov.afip.dif.FEV1/", "FEDummy").pyclass

FEDummySoapOut = GED("http://ar.gov.afip.dif.FEV1/", "FEDummyResponse").pyclass

FECompUltimoAutorizadoSoapIn = GED("http://ar.gov.afip.dif.FEV1/", "FECompUltimoAutorizado").pyclass

FECompUltimoAutorizadoSoapOut = GED("http://ar.gov.afip.dif.FEV1/", "FECompUltimoAutorizadoResponse").pyclass

FECompConsultarSoapIn = GED("http://ar.gov.afip.dif.FEV1/", "FECompConsultar").pyclass

FECompConsultarSoapOut = GED("http://ar.gov.afip.dif.FEV1/", "FECompConsultarResponse").pyclass

FECAEARegInformativoSoapIn = GED("http://ar.gov.afip.dif.FEV1/", "FECAEARegInformativo").pyclass

FECAEARegInformativoSoapOut = GED("http://ar.gov.afip.dif.FEV1/", "FECAEARegInformativoResponse").pyclass

FECAEASolicitarSoapIn = GED("http://ar.gov.afip.dif.FEV1/", "FECAEASolicitar").pyclass

FECAEASolicitarSoapOut = GED("http://ar.gov.afip.dif.FEV1/", "FECAEASolicitarResponse").pyclass

FECAEASinMovimientoConsultarSoapIn = GED("http://ar.gov.afip.dif.FEV1/", "FECAEASinMovimientoConsultar").pyclass

FECAEASinMovimientoConsultarSoapOut = GED("http://ar.gov.afip.dif.FEV1/", "FECAEASinMovimientoConsultarResponse").pyclass

FECAEASinMovimientoInformarSoapIn = GED("http://ar.gov.afip.dif.FEV1/", "FECAEASinMovimientoInformar").pyclass

FECAEASinMovimientoInformarSoapOut = GED("http://ar.gov.afip.dif.FEV1/", "FECAEASinMovimientoInformarResponse").pyclass

FECAEAConsultarSoapIn = GED("http://ar.gov.afip.dif.FEV1/", "FECAEAConsultar").pyclass

FECAEAConsultarSoapOut = GED("http://ar.gov.afip.dif.FEV1/", "FECAEAConsultarResponse").pyclass

FEParamGetCotizacionSoapIn = GED("http://ar.gov.afip.dif.FEV1/", "FEParamGetCotizacion").pyclass

FEParamGetCotizacionSoapOut = GED("http://ar.gov.afip.dif.FEV1/", "FEParamGetCotizacionResponse").pyclass

FEParamGetTiposTributosSoapIn = GED("http://ar.gov.afip.dif.FEV1/", "FEParamGetTiposTributos").pyclass

FEParamGetTiposTributosSoapOut = GED("http://ar.gov.afip.dif.FEV1/", "FEParamGetTiposTributosResponse").pyclass

FEParamGetTiposMonedasSoapIn = GED("http://ar.gov.afip.dif.FEV1/", "FEParamGetTiposMonedas").pyclass

FEParamGetTiposMonedasSoapOut = GED("http://ar.gov.afip.dif.FEV1/", "FEParamGetTiposMonedasResponse").pyclass

FEParamGetTiposIvaSoapIn = GED("http://ar.gov.afip.dif.FEV1/", "FEParamGetTiposIva").pyclass

FEParamGetTiposIvaSoapOut = GED("http://ar.gov.afip.dif.FEV1/", "FEParamGetTiposIvaResponse").pyclass

FEParamGetTiposOpcionalSoapIn = GED("http://ar.gov.afip.dif.FEV1/", "FEParamGetTiposOpcional").pyclass

FEParamGetTiposOpcionalSoapOut = GED("http://ar.gov.afip.dif.FEV1/", "FEParamGetTiposOpcionalResponse").pyclass

FEParamGetTiposConceptoSoapIn = GED("http://ar.gov.afip.dif.FEV1/", "FEParamGetTiposConcepto").pyclass

FEParamGetTiposConceptoSoapOut = GED("http://ar.gov.afip.dif.FEV1/", "FEParamGetTiposConceptoResponse").pyclass

FEParamGetPtosVentaSoapIn = GED("http://ar.gov.afip.dif.FEV1/", "FEParamGetPtosVenta").pyclass

FEParamGetPtosVentaSoapOut = GED("http://ar.gov.afip.dif.FEV1/", "FEParamGetPtosVentaResponse").pyclass

FEParamGetTiposCbteSoapIn = GED("http://ar.gov.afip.dif.FEV1/", "FEParamGetTiposCbte").pyclass

FEParamGetTiposCbteSoapOut = GED("http://ar.gov.afip.dif.FEV1/", "FEParamGetTiposCbteResponse").pyclass

FEParamGetTiposDocSoapIn = GED("http://ar.gov.afip.dif.FEV1/", "FEParamGetTiposDoc").pyclass

FEParamGetTiposDocSoapOut = GED("http://ar.gov.afip.dif.FEV1/", "FEParamGetTiposDocResponse").pyclass


# Service Skeletons
class Service(ServiceSOAPBinding):
    soapAction = {}
    root = {}

    def __init__(self, post='/wsfev1/service.asmx', **kw):
        ServiceSOAPBinding.__init__(self, post)

    def soap_FECAESolicitar(self, ps, **kw):
        request = ps.Parse(FECAESolicitarSoapIn.typecode)
        return request,FECAESolicitarSoapOut()

    soapAction['http://ar.gov.afip.dif.FEV1/FECAESolicitar'] = 'soap_FECAESolicitar'
    root[(FECAESolicitarSoapIn.typecode.nspname,FECAESolicitarSoapIn.typecode.pname)] = 'soap_FECAESolicitar'

    def soap_FECompTotXRequest(self, ps, **kw):
        request = ps.Parse(FECompTotXRequestSoapIn.typecode)
        return request,FECompTotXRequestSoapOut()

    soapAction['http://ar.gov.afip.dif.FEV1/FECompTotXRequest'] = 'soap_FECompTotXRequest'
    root[(FECompTotXRequestSoapIn.typecode.nspname,FECompTotXRequestSoapIn.typecode.pname)] = 'soap_FECompTotXRequest'

    def soap_FEDummy(self, ps, **kw):
        request = ps.Parse(FEDummySoapIn.typecode)
        return request,FEDummySoapOut()

    soapAction['http://ar.gov.afip.dif.FEV1/FEDummy'] = 'soap_FEDummy'
    root[(FEDummySoapIn.typecode.nspname,FEDummySoapIn.typecode.pname)] = 'soap_FEDummy'

    def soap_FECompUltimoAutorizado(self, ps, **kw):
        request = ps.Parse(FECompUltimoAutorizadoSoapIn.typecode)
        return request,FECompUltimoAutorizadoSoapOut()

    soapAction['http://ar.gov.afip.dif.FEV1/FECompUltimoAutorizado'] = 'soap_FECompUltimoAutorizado'
    root[(FECompUltimoAutorizadoSoapIn.typecode.nspname,FECompUltimoAutorizadoSoapIn.typecode.pname)] = 'soap_FECompUltimoAutorizado'

    def soap_FECompConsultar(self, ps, **kw):
        request = ps.Parse(FECompConsultarSoapIn.typecode)
        return request,FECompConsultarSoapOut()

    soapAction['http://ar.gov.afip.dif.FEV1/FECompConsultar'] = 'soap_FECompConsultar'
    root[(FECompConsultarSoapIn.typecode.nspname,FECompConsultarSoapIn.typecode.pname)] = 'soap_FECompConsultar'

    def soap_FECAEARegInformativo(self, ps, **kw):
        request = ps.Parse(FECAEARegInformativoSoapIn.typecode)
        return request,FECAEARegInformativoSoapOut()

    soapAction['http://ar.gov.afip.dif.FEV1/FECAEARegInformativo'] = 'soap_FECAEARegInformativo'
    root[(FECAEARegInformativoSoapIn.typecode.nspname,FECAEARegInformativoSoapIn.typecode.pname)] = 'soap_FECAEARegInformativo'

    def soap_FECAEASolicitar(self, ps, **kw):
        request = ps.Parse(FECAEASolicitarSoapIn.typecode)
        return request,FECAEASolicitarSoapOut()

    soapAction['http://ar.gov.afip.dif.FEV1/FECAEASolicitar'] = 'soap_FECAEASolicitar'
    root[(FECAEASolicitarSoapIn.typecode.nspname,FECAEASolicitarSoapIn.typecode.pname)] = 'soap_FECAEASolicitar'

    def soap_FECAEASinMovimientoConsultar(self, ps, **kw):
        request = ps.Parse(FECAEASinMovimientoConsultarSoapIn.typecode)
        return request,FECAEASinMovimientoConsultarSoapOut()

    soapAction['http://ar.gov.afip.dif.FEV1/FECAEASinMovimientoConsultar'] = 'soap_FECAEASinMovimientoConsultar'
    root[(FECAEASinMovimientoConsultarSoapIn.typecode.nspname,FECAEASinMovimientoConsultarSoapIn.typecode.pname)] = 'soap_FECAEASinMovimientoConsultar'

    def soap_FECAEASinMovimientoInformar(self, ps, **kw):
        request = ps.Parse(FECAEASinMovimientoInformarSoapIn.typecode)
        return request,FECAEASinMovimientoInformarSoapOut()

    soapAction['http://ar.gov.afip.dif.FEV1/FECAEASinMovimientoInformar'] = 'soap_FECAEASinMovimientoInformar'
    root[(FECAEASinMovimientoInformarSoapIn.typecode.nspname,FECAEASinMovimientoInformarSoapIn.typecode.pname)] = 'soap_FECAEASinMovimientoInformar'

    def soap_FECAEAConsultar(self, ps, **kw):
        request = ps.Parse(FECAEAConsultarSoapIn.typecode)
        return request,FECAEAConsultarSoapOut()

    soapAction['http://ar.gov.afip.dif.FEV1/FECAEAConsultar'] = 'soap_FECAEAConsultar'
    root[(FECAEAConsultarSoapIn.typecode.nspname,FECAEAConsultarSoapIn.typecode.pname)] = 'soap_FECAEAConsultar'

    def soap_FEParamGetCotizacion(self, ps, **kw):
        request = ps.Parse(FEParamGetCotizacionSoapIn.typecode)
        return request,FEParamGetCotizacionSoapOut()

    soapAction['http://ar.gov.afip.dif.FEV1/FEParamGetCotizacion'] = 'soap_FEParamGetCotizacion'
    root[(FEParamGetCotizacionSoapIn.typecode.nspname,FEParamGetCotizacionSoapIn.typecode.pname)] = 'soap_FEParamGetCotizacion'

    def soap_FEParamGetTiposTributos(self, ps, **kw):
        request = ps.Parse(FEParamGetTiposTributosSoapIn.typecode)
        return request,FEParamGetTiposTributosSoapOut()

    soapAction['http://ar.gov.afip.dif.FEV1/FEParamGetTiposTributos'] = 'soap_FEParamGetTiposTributos'
    root[(FEParamGetTiposTributosSoapIn.typecode.nspname,FEParamGetTiposTributosSoapIn.typecode.pname)] = 'soap_FEParamGetTiposTributos'

    def soap_FEParamGetTiposMonedas(self, ps, **kw):
        request = ps.Parse(FEParamGetTiposMonedasSoapIn.typecode)
        return request,FEParamGetTiposMonedasSoapOut()

    soapAction['http://ar.gov.afip.dif.FEV1/FEParamGetTiposMonedas'] = 'soap_FEParamGetTiposMonedas'
    root[(FEParamGetTiposMonedasSoapIn.typecode.nspname,FEParamGetTiposMonedasSoapIn.typecode.pname)] = 'soap_FEParamGetTiposMonedas'

    def soap_FEParamGetTiposIva(self, ps, **kw):
        request = ps.Parse(FEParamGetTiposIvaSoapIn.typecode)
        return request,FEParamGetTiposIvaSoapOut()

    soapAction['http://ar.gov.afip.dif.FEV1/FEParamGetTiposIva'] = 'soap_FEParamGetTiposIva'
    root[(FEParamGetTiposIvaSoapIn.typecode.nspname,FEParamGetTiposIvaSoapIn.typecode.pname)] = 'soap_FEParamGetTiposIva'

    def soap_FEParamGetTiposOpcional(self, ps, **kw):
        request = ps.Parse(FEParamGetTiposOpcionalSoapIn.typecode)
        return request,FEParamGetTiposOpcionalSoapOut()

    soapAction['http://ar.gov.afip.dif.FEV1/FEParamGetTiposOpcional'] = 'soap_FEParamGetTiposOpcional'
    root[(FEParamGetTiposOpcionalSoapIn.typecode.nspname,FEParamGetTiposOpcionalSoapIn.typecode.pname)] = 'soap_FEParamGetTiposOpcional'

    def soap_FEParamGetTiposConcepto(self, ps, **kw):
        request = ps.Parse(FEParamGetTiposConceptoSoapIn.typecode)
        return request,FEParamGetTiposConceptoSoapOut()

    soapAction['http://ar.gov.afip.dif.FEV1/FEParamGetTiposConcepto'] = 'soap_FEParamGetTiposConcepto'
    root[(FEParamGetTiposConceptoSoapIn.typecode.nspname,FEParamGetTiposConceptoSoapIn.typecode.pname)] = 'soap_FEParamGetTiposConcepto'

    def soap_FEParamGetPtosVenta(self, ps, **kw):
        request = ps.Parse(FEParamGetPtosVentaSoapIn.typecode)
        return request,FEParamGetPtosVentaSoapOut()

    soapAction['http://ar.gov.afip.dif.FEV1/FEParamGetPtosVenta'] = 'soap_FEParamGetPtosVenta'
    root[(FEParamGetPtosVentaSoapIn.typecode.nspname,FEParamGetPtosVentaSoapIn.typecode.pname)] = 'soap_FEParamGetPtosVenta'

    def soap_FEParamGetTiposCbte(self, ps, **kw):
        request = ps.Parse(FEParamGetTiposCbteSoapIn.typecode)
        return request,FEParamGetTiposCbteSoapOut()

    soapAction['http://ar.gov.afip.dif.FEV1/FEParamGetTiposCbte'] = 'soap_FEParamGetTiposCbte'
    root[(FEParamGetTiposCbteSoapIn.typecode.nspname,FEParamGetTiposCbteSoapIn.typecode.pname)] = 'soap_FEParamGetTiposCbte'

    def soap_FEParamGetTiposDoc(self, ps, **kw):
        request = ps.Parse(FEParamGetTiposDocSoapIn.typecode)
        return request,FEParamGetTiposDocSoapOut()

    soapAction['http://ar.gov.afip.dif.FEV1/FEParamGetTiposDoc'] = 'soap_FEParamGetTiposDoc'
    root[(FEParamGetTiposDocSoapIn.typecode.nspname,FEParamGetTiposDocSoapIn.typecode.pname)] = 'soap_FEParamGetTiposDoc'

