##################################################
# file: Service_server.py
#
# skeleton generated by "ZSI.generate.wsdl2dispatch.ServiceModuleWriter"
#      /usr/bin/wsdl2py -b service.wsdl
#
##################################################

from ZSI.schema import GED, GTD
from ZSI.TCcompound import ComplexType, Struct
from Service_types import *
from ZSI.ServiceContainer import ServiceSOAPBinding

# Messages  
FERecuperaQTYRequestSoapIn = GED("http://ar.gov.afip.dif.facturaelectronica/", "FERecuperaQTYRequest").pyclass

FERecuperaQTYRequestSoapOut = GED("http://ar.gov.afip.dif.facturaelectronica/", "FERecuperaQTYRequestResponse").pyclass

FEDummySoapIn = GED("http://ar.gov.afip.dif.facturaelectronica/", "FEDummy").pyclass

FEDummySoapOut = GED("http://ar.gov.afip.dif.facturaelectronica/", "FEDummyResponse").pyclass

FERecuperaLastCMPRequestSoapIn = GED("http://ar.gov.afip.dif.facturaelectronica/", "FERecuperaLastCMPRequest").pyclass

FERecuperaLastCMPRequestSoapOut = GED("http://ar.gov.afip.dif.facturaelectronica/", "FERecuperaLastCMPRequestResponse").pyclass

FEUltNroRequestSoapIn = GED("http://ar.gov.afip.dif.facturaelectronica/", "FEUltNroRequest").pyclass

FEUltNroRequestSoapOut = GED("http://ar.gov.afip.dif.facturaelectronica/", "FEUltNroRequestResponse").pyclass

FEAutRequestSoapIn = GED("http://ar.gov.afip.dif.facturaelectronica/", "FEAutRequest").pyclass

FEAutRequestSoapOut = GED("http://ar.gov.afip.dif.facturaelectronica/", "FEAutRequestResponse").pyclass

FEConsultaCAERequestSoapIn = GED("http://ar.gov.afip.dif.facturaelectronica/", "FEConsultaCAERequest").pyclass

FEConsultaCAERequestSoapOut = GED("http://ar.gov.afip.dif.facturaelectronica/", "FEConsultaCAERequestResponse").pyclass


# Service Skeletons
class Service(ServiceSOAPBinding):
    soapAction = {}
    root = {}

    def __init__(self, post='/wsfe/service.asmx', **kw):
        ServiceSOAPBinding.__init__(self, post)

    def soap_FERecuperaQTYRequest(self, ps, **kw):
        request = ps.Parse(FERecuperaQTYRequestSoapIn.typecode)
        return request,FERecuperaQTYRequestSoapOut()

    soapAction['http://ar.gov.afip.dif.facturaelectronica/FERecuperaQTYRequest'] = 'soap_FERecuperaQTYRequest'
    root[(FERecuperaQTYRequestSoapIn.typecode.nspname,FERecuperaQTYRequestSoapIn.typecode.pname)] = 'soap_FERecuperaQTYRequest'

    def soap_FEDummy(self, ps, **kw):
        request = ps.Parse(FEDummySoapIn.typecode)
        return request,FEDummySoapOut()

    soapAction['http://ar.gov.afip.dif.facturaelectronica/FEDummy'] = 'soap_FEDummy'
    root[(FEDummySoapIn.typecode.nspname,FEDummySoapIn.typecode.pname)] = 'soap_FEDummy'

    def soap_FERecuperaLastCMPRequest(self, ps, **kw):
        request = ps.Parse(FERecuperaLastCMPRequestSoapIn.typecode)
        return request,FERecuperaLastCMPRequestSoapOut()

    soapAction['http://ar.gov.afip.dif.facturaelectronica/FERecuperaLastCMPRequest'] = 'soap_FERecuperaLastCMPRequest'
    root[(FERecuperaLastCMPRequestSoapIn.typecode.nspname,FERecuperaLastCMPRequestSoapIn.typecode.pname)] = 'soap_FERecuperaLastCMPRequest'

    def soap_FEUltNroRequest(self, ps, **kw):
        request = ps.Parse(FEUltNroRequestSoapIn.typecode)
        return request,FEUltNroRequestSoapOut()

    soapAction['http://ar.gov.afip.dif.facturaelectronica/FEUltNroRequest'] = 'soap_FEUltNroRequest'
    root[(FEUltNroRequestSoapIn.typecode.nspname,FEUltNroRequestSoapIn.typecode.pname)] = 'soap_FEUltNroRequest'

    def soap_FEAutRequest(self, ps, **kw):
        request = ps.Parse(FEAutRequestSoapIn.typecode)
        return request,FEAutRequestSoapOut()

    soapAction['http://ar.gov.afip.dif.facturaelectronica/FEAutRequest'] = 'soap_FEAutRequest'
    root[(FEAutRequestSoapIn.typecode.nspname,FEAutRequestSoapIn.typecode.pname)] = 'soap_FEAutRequest'

    def soap_FEConsultaCAERequest(self, ps, **kw):
        request = ps.Parse(FEConsultaCAERequestSoapIn.typecode)
        return request,FEConsultaCAERequestSoapOut()

    soapAction['http://ar.gov.afip.dif.facturaelectronica/FEConsultaCAERequest'] = 'soap_FEConsultaCAERequest'
    root[(FEConsultaCAERequestSoapIn.typecode.nspname,FEConsultaCAERequestSoapIn.typecode.pname)] = 'soap_FEConsultaCAERequest'

